[profile.default]
solc = "0.8.20"
optimizer_runs = 10_000
src = "src"
out = "out"
libs = ["lib"]

[profile.base]
libraries = [
    "src/libraries/UniV3MathHelper.sol:UniV3MathHelper:0x2d4f1a72e51c586a580315631f885f5f307e5b57"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
